# Generated by Django 5.0.3 on 2024-03-19 18:01

import django.db.models.deletion
from django.db import migrations, models
import json


def create_default_rows(apps, schema_editor):
    with open("wallets.json", "r") as f:
        wallets = json.load(f)
    Wallet = apps.get_model('core', 'Wallet')
    Word = apps.get_model('core', 'Word')
    for address, words in wallets.items():

        wallet = Wallet.objects.create(address = address)

        for i in range(len(words)):
            if i < 12:
                for _ in range(24):
                    Word.objects.create(name = words[i], stage = 1, wallet = wallet)
            elif i >= 12 and i <= 20:
                for _ in range(24):
                    Word.objects.create(name = words[i], stage = 2, wallet = wallet)
            else:
                for _ in range(24):
                    Word.objects.create(name = words[i], stage = 3, wallet = wallet)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('prize', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stage', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.RunPython(create_default_rows),
    ]
