# Generated by Django 4.2.11 on 2024-04-06 12:05

from django.db import migrations, models
import django.db.models.deletion
import json
import openpyxl

def create_default_rows(apps, schema_editor):
    with open("wallets.json", "r") as f:
        wallets = json.load(f)
    Wallet = apps.get_model('core', 'Wallet')
    Word = apps.get_model('core', 'Word')
    for address, words in wallets.items():

        wallet = Wallet.objects.create(address = address)

        for i in range(len(words)):
            for _ in range(24):
                Word.objects.create(name = words[i], wallet = wallet)




def setindex(apps, schema_editor):
    wb = openpyxl.load_workbook('json.xlsx', data_only=True)

    Word = apps.get_model('core', 'Word')

    sheet = wb["json v2"]

    
    for i in range(1, 13825):
        words = Word.objects.filter(wallet_id = sheet[f"C{i}"].value) & Word.objects.filter(index = None)
        word = words.first()
        word.index = int(sheet[f"K{i}"].value) - 1
        word.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('prize', models.FloatField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('index', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.RunPython(create_default_rows),
        migrations.RunPython(setindex),
    ]
